cloud/cloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_nbm/', include('my_nbm.urls')),
    path('', RedirectView.as_view(url='/accounts/login/?next=/my_nbm/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

cloud/my_nbm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_new/', views.new_analysis, name='new'),
    path('pending/', views.AnalysisListView.as_view(template_name="my_nbm/pending_list.html"), name='pending'),
    path('completed/', views.AnalysisListView.as_view(template_name="my_nbm/completed_list.html"), name='completed'),
    path('analysis/<uuid:pk>', views.AnalysisDetailView.as_view(), name='analysis-detail'),
    path('analysis/create/', views.AnalysisCreate.as_view(), name='analysis_create'),
    path('analysis/<int:pk>/update/', views.AnalysisUpdate.as_view(), name='analysis_update'),
    path('analysis/<int:pk>/delete/', views.AnalysisDelete.as_view(), name='analysis_delete'),
]

cloud/my_nbm/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Analysis(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique Id for the Analysis")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    submission_date = models.DateField(null=True, blank=True)
    co_ord = models.TextField (max_length=50)
    depth = models.IntegerField()	
    n_els = models.TextField (max_length=20)
    n_el_l = models.TextField (max_length=20)
    El=models.IntegerField()
    nu=models.CharField(max_length=5)
    Fy=models.IntegerField()
    
    Boundary_Condition = (
        ('p', 'pin'),
        ('f', 'fix'),
    )
    BC = models.CharField(max_length=1, choices=Boundary_Condition, blank=True, default='p', help_text='Boundary Condition')	
	
    analysistype = (
        ('b', 'buckle'),
        ('s', 'static'),
    )
    Analysis_type = models.CharField(max_length=1, choices=analysistype, blank=True, default='s', help_text='Analysis Type')	
	
    testtype= (
        ('b', 'bend'),
        ('s', 'shear'),
        ('u', 'uniform'),
    )
    Test_type = models.CharField(max_length=1, choices=testtype, blank=True, default='s', help_text='Boundary Condition')	
	
    o_stress = models.CharField(max_length=200)
    o_strain = models.CharField(max_length=200)
    
	
	
    ANALYSIS_STATUS = (
        ('p', 'Pending'),
        ('c', 'Completed'),
    )

    status = models.CharField(max_length=1, choices=ANALYSIS_STATUS, blank=True, default='p', help_text='Analysis Status')

    class Meta:
        ordering = ["submission_date","status"]
      
    def __str__(self):
        """
        String for representing the Model object
        """
        return '{0} ({1}) // {2} // {3}'.format(self.owner,self.submission_date,self.status,self.id)
	
    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this Analysis.
        """
        return reverse('analysis-detail', args=[str(self.id)])

cloud/my_nbm/forms.py
from django import forms

class CreateNewAnalysis(forms.Form):
    nodes = forms.CharField(required = True,help_text="Enter the array.")
    elements = forms.CharField(help_text="Enter the array.")

cloud/my_nbm/views.py
from django.shortcuts import render

# Create your views here.
from .models import Analysis
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.conf import settings
from .forms import CreateNewAnalysis
import datetime
#from django.contrib.auth.models import user

#login_required
def index(request):
    """
    View function for home page of site.
    """
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    # Generate counts of some of the main objects
    num_pending=Analysis.objects.filter(status__exact='p').filter(owner=request.user).count()
    num_completed=Analysis.objects.filter(status__exact='c').filter(owner=request.user).count()
	
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_pending':num_pending,'num_completed':num_completed,'num_visits':num_visits},
		)
	
class AnalysisListView(LoginRequiredMixin,generic.ListView):
    model = Analysis
    def get_queryset(self):
        return Analysis.objects.filter(owner=self.request.user)


class AnalysisDetailView(LoginRequiredMixin,generic.DetailView):
    model = Analysis
    def get_queryset(self):
        return Analysis.objects.filter(owner=self.request.user)

def new_analysis(request):
    if request.method == 'POST':
        form  = CreateNewAnalysis(request.POST)
    else:
        form  = CreateNewAnalysis(initial={'nodes': '23',})
    return render(request,'my_nbm/create_new.html',{'form':form})

class AnalysisCreate(CreateView):
    model = Analysis
    fields = '__all__'
    initial={'submission_date':datetime.date.today(),'status':'p','co_ord':'[-2 4.5 0;-2 5 0;0 5 0;0 0 0;2 0 0;2 .5 0]','depth':10,'n_els':'[3 4 6 4 3]','n_el_l':20,'El':29500,'nu':0.3,'Fy':50}

class AnalysisUpdate(UpdateView):
    model = Analysis
    fields = ['submission_date','node','element','o_stress','o_strain','status']

class AnalysisDelete(DeleteView):
    model = Analysis
    success_url = reverse_lazy('index')
	
'''
    def analysis_detail_view(request,pk):
        try:
            analysis_id=Analysis.objects.get(pk=pk)
        except analysis.DoesNotExist:
            raise Http404("Analysis does not exist")

        #book_id=get_object_or_404(Book, pk=pk)
      
        return render(
            request,
            'my_nbm/analysis_detail.html',
            context={'analysis':analysis_id,}
    )
'''

	
	
	
	

cloud/my_nbm/templates/base_login.html
<!DOCTYPE html>
<html>

<head>
{% load static %}
  <meta charset="UTF-8">

  <title>NBM - Login </title>

  <link rel="stylesheet" href="{% static 'login/css/reset.css' %}">

    <link rel="stylesheet" href="{% static 'login/css/style.css' %}" media="screen" type="text/css" />

</head>

<body>

  <div class="wrap">
		<!--<div class="avatar">
      <img src="http://cdn.ialireza.me/avatar.png">
		</div>-->
		{% block content %}{% endblock %}
	</div>

  <!--<script src="{% static 'js/index.js' %}"></script> -->

</body>

</html>

cloud/my_nbm/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h2>NBM Technologies Inc.</h2>

  <p>Welcome to <em>NBM Technologies</em>, an online platform for Structural Solutions.</p>

<h1>An Overview</h1>

  <p>The platform has the following record counts:</p>
  <ul>
    <li><strong>Pending Analysis:</strong> {{ num_pending }}</li>
    <li><strong>Completed Analysis:</strong> {{ num_completed }}</li>
  </ul>
  
  
  <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}

cloud/my_nbm/templates/my_nbm/analysis_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Analysis</h1>

<p>Are you sure you want to delete the analysis: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

cloud/my_nbm/templates/my_nbm/analysis_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Analysis: {{ analysis.owner }} / {{ analysis.submission_date }}</h1>
  
  <p><strong>Id:</strong> {{ analysis.id }}</p>
  
  <p><strong>Coordinate:</strong> <a href="">{{ analysis.co_ord }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Depth:</strong> {{ analysis.depth }}</p>
  <p><strong>n_els:</strong>{{ analysis.n_els }}</p>
  <p><strong>n_el_l:</strong> {{ analysis.n_el_l }}</p>
  <p><strong>El:</strong>{{ analysis.El }}</p> 
  <p><strong>nu:</strong> {{ analysis.nu }}</p>
  <p><strong>Fy:</strong>{{ analysis.Fy }}</p>
  <p><strong>Boundary Conditons:</strong> {{ analysis.BC }}</p>
  <p><strong>Analysis Type:</strong>{{ analysis.Analysis_type }}</p>
  <p><strong>Test Type:</strong> {{ analysis.Test_type }}</p>
  <br></br>
  <p><strong>Output Stress:</strong> {{ analysis.o_stress }}</p> 
  <p><strong>Output Strain:</strong> {{ analysis.o_strain }}</p>  
  <p><strong>Status:</strong> {{ analysis.status }} </p>  
<!--
  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
-->
{% endblock %}

cloud/my_nbm/templates/my_nbm/analysis_form.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Create New Project: {{ request.user }} </h1>
<br></br>
<br></br>

<form action="" method="post">
    {% csrf_token %}
    <table id="text-val">
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" id="dwn-btn"/>
    
</form>

<script>
function download(filename, text) {
  var element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

document.getElementById("dwn-btn").addEventListener("click", function(){
    // Generate download of hello.txt file with some content
    <!-- var text = document.getElementById("text-val").value; -->
	 
	<!-- var text = table.rows[1].cells[1].innerHTML  -->
    <!-- for(var i=1; i<5;i++){-->
    <!--    text = table.rows[2].cells[1].firstChild.value-->
    <!--}-->
	var table = document.getElementById("text-val")
    tableArr = new Array();
    for(var i=3; i<10;i++){
        tableArr.push([table.rows[i].cells[1].firstChild.value])
    }
    text = tableArr
    var filename = "hello.txt";
    
    download(filename, text);
}, false);

</script>


{% endblock %}

cloud/my_nbm/templates/my_nbm/completed_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Completed List</h1>

    {% if analysis_list %}
    <ul>

      {% for analysis in analysis_list %}
	    {% if analysis.status == 'c' %}
      <li>
        <a href="{{ analysis.get_absolute_url }}">{{ analysis.submission_date }}</a> ({{analysis.status}})
		{% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no analysis in the completed list.</p>
    {% endif %}       
{% endblock %}

cloud/my_nbm/templates/my_nbm/create_new.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Create New Project: {{ request.user }} </h1>
  
  <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

   
  
<!--
  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
-->
{% endblock %}

cloud/my_nbm/templates/my_nbm/pending_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Pending List</h1>
	
    {% if analysis_list %}
    <ul>
	
      {% for analysis in analysis_list %}
	    {% if analysis.status == 'p' %}
      <li>
        <a href="{{ analysis.get_absolute_url }}">{{ analysis.submission_date }}</a> ({{analysis.status}})
		{% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no analysis in the pending list.</p>
    {% endif %}       
{% endblock %}

cloud/my_nbm/templates/test4.html
<!DOCTYPE html>
<html>
<body>

<p>Enter names in the fields, then click "Submit" to submit the form:</p>

<textarea id="text-val" rows="4">This is the content of my file</textarea><br/>
<input type="button" id="dwn-btn" value="Download dinamically generated text file"/>

<script>
function download(filename, text) {
  var element = document.createElement('a');
  
  var name = document.getElementById("name").value;
  var email = document.getElementById("email").value;
  var password = document.getElementById("password").value;
  var contact = document.getElementById("contact").value;

  var dataString = 'name1=' + name + '&email1=' + email + '&password1=' + password + '&contact1=' + contact;
  
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

document.getElementById("dwn-btn").addEventListener("click", function(){
    // Generate download of hello.txt file with some content
    var text = document.getElementById("text-val").value;
    var filename = "hello.txt";
    
    download(filename, text);
}, false);

</script>

</body>
</html>

cloud/my_nbm/templates/text.html
<!DOCTYPE>
<html>
<head></head>
<script language="javascript">


function download(filename, text) {
  var element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}
</script>

<body onLoad="WriteToFile()">
<textarea id="text-val" rows="4" name = 'contentss'>This is the content of my file</textarea><br/>
<input type="button" id="dwn-btn" value="Download" onclick='download("hello.txt","contentss")'/>
</body>

</html>

cloud/my_nbm/templates/text2.html
<!DOCTYPE html>
<html>
<body>

<p>Enter names in the fields, then click "Submit" to submit the form:</p>

<form id="frm1" action="/action_page.php">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br><br>
  <input type="button" id="dwn-btn" value="Submit">
</form>

<script>
function download(filename, text) {
  var element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

document.getElementById("dwn-btn").addEventListener("click", function(){
    // Generate download of hello.txt file with some content
    var text = document.getElementById("frm1").value;
    var filename = "hello.txt";
    
    download(filename, text);
}, false);

</script>

</body>
</html>

cloud/my_nbm/templates/text3.html
<!DOCTYPE html>
<html>
<body>

<p>Enter names in the fields, then click "Submit" to submit the form:</p>

<textarea id="text-val" rows="4">This is the content of my file</textarea><br/>
<input type="button" id="dwn-btn" value="Download dinamically generated text file"/>

<script>
function download(filename, text) {
  var element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

document.getElementById("dwn-btn").addEventListener("click", function(){
    // Generate download of hello.txt file with some content
    var text = document.getElementById("text-val").value;
    var filename = "hello.txt";
    
    download(filename, text);
}, false);

</script>

</body>
</html>